ARG runbase=myclaw-run

FROM $runbase

RUN <<EOF
    set -euo pipefail
    export DEBIAN_FRONTEND=noninteractive

    apt-get update && apt-get -y dist-upgrade && apt-get -y install \
        build-essential \
        cargo \
        golang \
        maven \
        rustc \
        xvfb \

    apt-get clean
    apt-get dist-clean

EOF
