ARG runbase=myclaw-run

FROM $runbase

RUN <<EOF
    set -euo pipefail

    f=/usr/local/bin/forgejo
    curl -fsSL -o $f.xz 'https://codeberg.org/forgejo/forgejo/releases/download/v14.0.3/forgejo-14.0.3-linux-amd64.xz'
    unxz $f.xz
    chmod +x $f

EOF
