ARG runbase=myclaw-run

FROM $runbase

RUN <<EOF
    set -euo pipefail
    export DEBIAN_FRONTEND=noninteractive

    apt-get update && apt-get -y dist-upgrade && apt-get -y install \
        build-essential \
        cargo \
        golang \
        maven \
        rustc \
        \
        autokey-gtk \
        autokey-qt \
        novnc \
        python3-dogtail \
        python3-pyatspi \
        python3-pyautogui \
        vncdotool \
        vncsnapshot \
        x11vnc \
        xautomation \
        xdo \
        xdotool \
        xvfb \
        xvkbd \

    apt-get clean
    apt-get dist-clean

EOF
