ARG runbase=myclaw-run

FROM $runbase

RUN <<EOF
    set -euo pipefail

    apk update && apk upgrade && apk add --no-cache \
        cargo \
        g++ \
        go \
        maven \
        rust \
        zig \

    apk cache purge

EOF
