ARG runbase=myclaw-run

FROM $runbase

RUN <<EOF
    set -euo pipefail

    f=/usr/local/bin/bifrost
    curl -4fL -o $f https://downloads.getmaxim.ai/bifrost/latest/linux/amd64/bifrost-http
    chmod +x $f
EOF
